### ISSUE TITLE
无法保存设置

### ISSUE THREAD

**Issue by Bronya0** [midoks/wp-cache-db#1]
很感谢作者开发了这个插件！
我安装后后台无法保存，点击保存刷新后还是未保存的状态

**Comment by midoks** [comment]
> 很感谢作者开发了这个插件！
> 我安装后后台无法保存，点击保存刷新后还是未保存的状态

*.有可能没有写权限。
有人反馈过，但没有人联系我。如果还未解决，邮件联系我：midoks@163.com，给我teamviewer信息控制权限。
